### ISSUE TITLE
how to use ？

### ISSUE THREAD

**Issue by QingHui653** [yuanying/tumblr-like#1]
please write how to use in README。

**Comment by yuanying** [comment]
Get tumblr's consumer key, consumer secret, token and token secret. 
Then, you can

```
TUMBLR_CONSUMER_KEY="replace here with consumer key"
TUMBLR_CONSUMER_SECRET="replace here with consumer secret"
TUMBLR_CONSUMER_TOKEN="replace here with consumer token"
TUMBLR_CONSUMER_TOKEN_SECRET="replace here with consumer token secret"
bundle install
bundle exec ruby download.rb
```

**Comment by QingHui653** [comment]
I have a java version，but I found that using an api would result in downloading a like post that is not enough. Many posts have disappeared.

I do not know whether the use of crawlers can download all
